#!/bin/bash
# Fix xauth problem with X forwarding.
# https://serverfault.com/questions/278743/ssh-x11-not-working
# Basically sshd doesn't do xauth when a rc file exists, so do it manually.
if read proto cookie && [ -n "$DISPLAY" ]; then
  if [ `echo $DISPLAY | cut -c1-10` = 'localhost:' ]; then
    # X11UseLocalhost=yes
    echo add unix:`echo $DISPLAY |
        cut -c11-` $proto $cookie
  else
    # X11UseLocalhost=no
    echo add $DISPLAY $proto $cookie
  fi | xauth -q -
fi

# Fix SSH auth socket location so agent forwarding works with tmux
# https://blog.testdouble.com/posts/2016-11-18-reconciling-tmux-and-ssh-agent-forwarding
# Update: this doesn't work when ssh between machines that share $HOME, removing.
# if test "$SSH_AUTH_SOCK" ; then
    # ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
# fi
